### ISSUE TITLE
Consumo de energia sem transmissão

### ISSUE THREAD

**Issue by jeronimoschmitz** [marciopamplona/ESP-iothink#1]
Verificado que o consumo de energia durante a leitura dos sensores (sem transmissão ao broker) é praticamente a mesma que durante a transmissão (70mA). Verificar se está implementada a função modem-sleep, pois conforme o datasheet o consumo deveria ser em torno de 15mA com a CPU em funcionamento e com o Wi-Fi desligado.

**Comment by marciopamplona** [comment]
Alteração na função de DeepSleep

**Comment by marciopamplona** [comment]
Corrigido no commit [https://github.com/marciopamplona/ESP-iothink/commit/4ecb88e7d9c8a956b2d3c29e20c28ae222a7202b](url)

Consumo em deep sleep: 202uA
Consumo com radio on: ~75mA
Consumo sem radio: 17mA
