### ISSUE TITLE
Consumo de energia SD card em Deep Sleep

### ISSUE THREAD

**Issue by jeronimoschmitz** [marciopamplona/ESP-iothink#2]
Verificado que quando o chip entra em Deep Sleep o cartão SD card acaba permanecendo com consumo de corrente em torno de 20mA.

**Comment by marciopamplona** [comment]
Corrigido, commit mencionado acima.

**Comment by marciopamplona** [comment]
Continua acontecendo.

**Comment by marciopamplona** [comment]
Não procede. Problema com cartão SD (característica de alguns cartões). 
Sempre testar o consumo do cartão em Sleep.
