### ISSUE TITLE
Modificar Status

### ISSUE THREAD

**Issue by jeronimoschmitz** [marciopamplona/ESP-iothink#29]
Alterar Status: 

Inserir configuração de habilitar status no write config, assim com esta opção habilitada o status será enviado automaticamente.

-Inserir na informação de status:
Wifi RSSI, informando seu valor;
syncinterval, informando seu valor.
sleepenable, informando status on ou off;

Retirar ou colocar em outro status
A informação das redes Wi-fi Scaneadas

**Comment by jeronimoschmitz** [comment]
Melhorando a alteração....

Inserir configuração de habilitar status no write config, assim com esta opção habilitada o status será enviado automaticamente.

-Inserir na informação de status:
Wifi RSSI
Sleep enabled

- Retirar ou colocar em outro status
A informação das redes Wi-fi Scaneadas

**Comment by marciopamplona** [comment]
Movido para git.desto.tech
