### ISSUE TITLE
Módulo entrando em reset após envio de write/status

### ISSUE THREAD

**Issue by jeronimoschmitz** [marciopamplona/ESP-iothink#30]
Identificado que ao enviar o comando de write/status o módulo entra em reset, ficando em loop.

ets Jan  8 2013,rst cause:4, boot mode:(3,0)
wdt reset
load 0x4010f000, len 1384, room 16

Para o módulo voltar a funcionar é necessário apagar a mensagem no broker.

Falha verificada com módulos de 1M e 4M de flash.

**Comment by marciopamplona** [comment]
Movido para git.desto.tech
