### ISSUE TITLE
Variáveis 

### ISSUE THREAD

**Issue by jeronimoschmitz** [marciopamplona/ESP-iothink#5]
1. Criar variável
chipid para inserir no tópico 

2. Alterar nome da variável 
measure para measuretag para inserir no tópico

O objetivo da mudança é de reduzir o valor do tamanho dos dados da transmissão MQTT.
O formato dos tópicos ficará conforme abaixo:
Subscribe: /%chipid%/write/#
Publish: /%chipid%/%systime%/%sensortag%/%measuretag%

**Comment by marciopamplona** [comment]
%chipid% em hexa

**Comment by marciopamplona** [comment]
Resolvido no commit acima.
